export enum ImplementacionNequi {
  NEQUI_CLIENT_ID = 'NEQUI_CLIENT_ID',
  NEQUI_CLIENT_SECRET = 'NEQUI_CLIENT_SECRET',
  NEQUI_API_KEY = 'NEQUI_API_KEY',
  NEQUI_AUTH_URI = 'NEQUI_AUTH_URI',
  NEQUI_UNREGISTERED_PAYMENT_URL = 'NEQUI_UNREGISTERED_PAYMENT_URL',
  NEQUI_CANCEL_PAYMENT_URL = 'NEQUI_CANCEL_PAYMENT_URL',
  NEQUI_STATUS_PAYMENT_URL =  'NEQUI_STATUS_PAYMENT_URL',
  NEQUI_REVERSE_PAYMENT_URL =  'NEQUI_REVERSE_PAYMENT_URL',
  NEQUI_PAYMENTS_QR_URL = 'NEQUI_PAYMENTS_QR_URL',
  NEQUI_STATUS_PAYMENTS_QR_URL = 'NEQUI_STATUS_PAYMENTS_QR_URL',
  NEQUI_REVERSE_PAYMENTS_QR_URL = 'NEQUI_REVERSE_PAYMENTS_QR_URL',
  NEQUI_TIMEUOT_CLOUD = 'NEQUI_TIMEUOT_CLOUD'
}